version: '3.9'

services:
  database:
    image: postgres
    container_name: observatory-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: observatory-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - observatory-db:/var/lib/postgresql/data      
volumes:
  observatory-db: